version: "3"
networks:
  unklab:
    external: true

services:
  nginx:
    container_name: nginx
    build:
      context: .
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - unklab
